"""empty message

Revision ID: 2bc342efc9de
Revises: b17c44d1d30e
Create Date: 2023-01-04 08:44:13.830680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc342efc9de'
down_revision = 'b17c44d1d30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.drop_column('max_guesses')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_guesses', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
