"""empty message

Revision ID: 682fd942bb28
Revises: 31bb87994945
Create Date: 2023-01-12 20:46:34.157281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682fd942bb28'
down_revision = '31bb87994945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
