"""empty message

Revision ID: b17c44d1d30e
Revises: 1ed010873717
Create Date: 2023-01-04 08:19:52.805793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17c44d1d30e'
down_revision = '1ed010873717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('max_guesses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'level', ['level_id'], ['id'])
        batch_op.drop_column('max_guesses')
        batch_op.drop_column('level')
        batch_op.drop_column('n_choices')
        batch_op.drop_column('code_length')

    with op.batch_alter_table('play', schema=None) as batch_op:
        batch_op.drop_constraint('play_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('id')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('play', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('play_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_length', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('n_choices', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_guesses', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('level_id')

    op.drop_table('level')
    # ### end Alembic commands ###
